### PR TITLE
Results card: create slim version

### PR DESCRIPTION
**Pull request by ajwl**
Pushing the datestamp onto the same line as the title of the card required much more rebuilding than I would like but 🤷‍♀️ 

I could no longer use the <ControlChange> component because its structure didn't give enough styling flexibility so have pasted it with a few adjustments in the <ResultsSummary>

New property `isSlim` controls if you see this or the default 

Datestamp span can be optionally bumped onto the next line with CSS injected from the client 

Screenshot 2024-10-04 at 17 01 31

### CODE REVIEW

**Comment by egargan** [comment]
Code changes look good! Though I tried out the `isSlim` prop in the Ticker component's stories and I've spotted a couple of visual issues that might need addressing, in Storybook at least.

| Screenshot | Notes |
| - | - |
|  | It seems the horizontal orientation stories show these overlapping summary items, it looks like this is because we're setting a fixed width (that `--ticker-width-item` variable), why do we need to do this again? Can't we just rely on flex? |
|  | The items aren't evenly-sized in the vertical layout, probably something that we could solve with flex again (`align-items: stretch` or something similar) |

**Comment by ajwl** [comment]
> Code changes look good! Though I tried out the `isSlim` prop in the Ticker component's stories and I've spotted a couple of visual issues that might need addressing, in Storybook at least.
> Screenshot 	Notes
>  	It seems the horizontal orientation stories show these overlapping summary items, it looks like this is because we're setting a fixed width (that `--ticker-width-item` variable), why do we need to do this again? Can't we just rely on flex?
>  	The items aren't evenly-sized in the vertical layout, probably something that we could solve with flex again (`align-items: stretch` or something similar)

Ah okay fair point. I probably have some override code in the US election repo, that isn't present in the component library. Will look into what we need to add

**Review by egargan — APPROVED** [review]
If we have this working in the US elections page I say let's just get this merged then fix the stories later!

**Comment by ajwl** [comment]
Thanks - will just merge this then and have chucked the Ticker story clean up in a separate PR: https://github.com/guardian/interactive-component-library/pull/292

**Pull request merged**
